name: Terraform Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'staging'
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3


      # Step 2: Install Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ var.TF_VER }}